project:
  type: website
  output-dir: docs
  
website:
  description: "Final R Portfolio for ESCI 222: Data storytelling & sustainable development"
  site-url: https://your-website-url.example.com
  title: "Home"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/burnssg0
      - icon: linkedin
        href: https://www.linkedin.com/in/sarah-grace-burns-006190368/
format:
  html:
    theme:
      - lux
      - brand
    css: styles.css

editor: visual

